[build]
command = "npm run build"  # Replace with your build command if necessary
publish = "public"  # Replace with the directory where your built files are located

[build.environment]
NODE_VERSION = "18"  # You can specify your Node.js version here

[context.production]
command = "npm start"  # Replace with your start command